# Generates web/maps_inject.js for Google Maps on Flutter web.
param(
  [string]$EnvFile = (Join-Path $PSScriptRoot "..\..\clicks-interface\.env"),
  [string]$LocalProperties = (Join-Path $PSScriptRoot "..\..\clicks-user\android\local.properties"),
  [switch]$Quiet
)

function Resolve-MapsKey {
  param([string]$Path, [string]$Pattern, [string]$Replace)
  if (-not (Test-Path $Path)) { return $null }
  $line = Get-Content $Path | Where-Object { $_ -match $Pattern } | Select-Object -First 1
  if (-not $line) { return $null }
  return ($line -replace $Replace, '').Trim().Trim('"').Trim("'")
}

$key = $null
if ($env:GOOGLE_MAPS_API_KEY) { $key = $env:GOOGLE_MAPS_API_KEY.Trim() }
elseif ($env:VITE_GOOGLE_MAPS_API_KEY) { $key = $env:VITE_GOOGLE_MAPS_API_KEY.Trim() }
else { $key = Resolve-MapsKey $EnvFile '^\s*VITE_GOOGLE_MAPS_API_KEY\s*=' '^\s*VITE_GOOGLE_MAPS_API_KEY\s*=\s*' }
if (-not $key) {
  $key = Resolve-MapsKey $LocalProperties '^GOOGLE_MAPS_API_KEY=' '^GOOGLE_MAPS_API_KEY='
}

if ([string]::IsNullOrWhiteSpace($key) -or $key -match 'REPLACE_|YOUR_') {
  Write-Error @"
Google Maps API key not found. Set one of:
  - clicks-interface/.env  (VITE_GOOGLE_MAPS_API_KEY=...)
  - clicks-user/android/local.properties  (GOOGLE_MAPS_API_KEY=...)
  - env GOOGLE_MAPS_API_KEY
"@
  exit 1
}

$outPath = Join-Path $PSScriptRoot "..\web\maps_inject.js"
$content = @"
// Auto-generated by scripts/enable-maps-web.ps1 — gitignored.
(function () {
  if (document.querySelector('script[data-clicks-maps]')) return;
  var s = document.createElement('script');
  s.setAttribute('data-clicks-maps', '1');
  s.src = 'https://maps.googleapis.com/maps/api/js?key=$key';
  s.async = true;
  s.defer = true;
  document.head.appendChild(s);
})();
"@
Set-Content -Path $outPath -Value $content -Encoding UTF8
if (-not $Quiet) { Write-Output "OK" }
