// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with actual Firebase config for clicks-user app
  // Run: flutterfire configure --project=clicks-d2da9
  // Or manually add the customer app in Firebase Console and update these values
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQEfWdyKvqjkH51FQ7LpYEbT6kj61Qma8',
    appId: '1:1076454306293:android:f41b5431ec3ba3a90a70bc',
    messagingSenderId: '1076454306293',
    projectId: 'clicks-d2da9',
    storageBucket: 'clicks-d2da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsBkv6H-JgQgCDs3w8x_Ax4spwVO1aN7Y',
    appId: '1:1076454306293:ios:668dc0964f6913490a70bc',
    messagingSenderId: '1076454306293',
    projectId: 'clicks-d2da9',
    storageBucket: 'clicks-d2da9.firebasestorage.app',
    iosBundleId: 'com.roya.clicksUser',
  );

}